spring.application.name=jwelery
server.port=${PORT:8080}
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.profiles.active=dev
# ===== File upload limits =====
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false